# Generated by Django 5.0.6 on 2024-06-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Имя клиента')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона')),
                ('date', models.CharField(blank=True, max_length=20, verbose_name='Дата')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='E-mail')),
            ],
        ),
    ]
