# Generated by Django 2.2.24 on 2024-06-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_order_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='volume',
            field=models.CharField(blank=True, max_length=30, verbose_name='Объем вещей'),
        ),
    ]
