# Generated by Django 2.2.24 on 2024-06-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_referrals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referrals',
            options={'verbose_name': 'реферал', 'verbose_name_plural': 'рефералы'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка'),
        ),
    ]
