# Generated by Django 2.2.24 on 2024-06-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20240629_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='referrals',
            options={'verbose_name': 'Реферал', 'verbose_name_plural': 'Рефералы'},
        ),
    ]
